### ISSUE TITLE
Dot-prefixed files and folders (e.g. `.well-known/`) aren't served from a Flutter site.

### ISSUE THREAD

**Issue by Namaneo** [appwrite/appwrite#10642]
### 👟 Reproduction steps

Although this bug looks similar to [this one](https://github.com/appwrite/appwrite/issues/10292), I've seen that this may be a broader issue with any file or folder prefixed with a dot (e.g. `.dotfile`, `.well-known/`, etc.). I've also seen some have reported this is working when using other runtimes, so this might be a Flutter-specific issue.

1. Create a Flutter site with an dot-prefixed file in the `web` folder.
2. Deploy it, and confirm the dot-prefixed file exists in the output directory.
3. Open `https://<domain>/.dotfile` or `https://<domain>/.well-known/assetlinks.json`.
4. See that an 404 Not Found error is returned.

### 👍 Expected behavior

It should serve dot-prefixed files and folders.

### 👎 Actual Behavior

It answers a 404 Not Found error for all dot-prefixed files and folders.

### 🎲 Appwrite version

Version 1.8.x

### 💻 Operating system

Linux

### 🧱 Your Environment

- I'm using Appwrite 1.8.0-RC2 (doesn't seem like there's any new relevant things in RC3).
- I confirmed that the `.well-known` directory and its content is present in the build directory.
- I'm deploying using the new Flutter-3.32 runtime.

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Namaneo thanks for raising this issue! 🙏🏼 Please keep in mind that the RC releases are for testing and aren't stable releases.

Things in a folder with a leading dot were excluded before because those folders are hidden. That said, we've changed it so they are included in the build. It should be working when 1.8.0 is released.

**Comment by Namaneo** [comment]
Thanks for answering!

Just updated to 1.8.0, I'd say this is now partially working, but the side that doesn't work is the one I would have preferred to work first. Ran a few deployments to see what's going on:
- Hidden files in the root directory are now being served, that's the working part.
- Files inside hidden folders are still not being served, so anything inside `.well-known/` can't be requested.

I confirmed the `.well-known/` folder ans its content are present in the build directory after the app has been successfully built. Maybe something is still missing to allow hidden folders content to be served?

**Comment by stnguyen90** [comment]
@Namaneo what do you have inside your well known folder that's not shown?

**Comment by Namaneo** [comment]
Just retried now: this seems to work. I believe last time I tried may have been unsuccessful because of a caching issue or something along those lines... Anyway, sorry for not having tried enough last time, and thanks for having fixed this! Closing as resolved.
