### ISSUE TITLE
Realtime throws diconnect error each second

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#1640]
## 🐛 Bug Report

Realtime appears to disconnect from the server all the time, leading to the following error being thrown each second:
```
app-all.js?v=160.0.10.1:12 Realtime got disconnected. Reconnect will be attempted in 1 second.
```
This issue seems to not only happen in testing or production environments but on the Appwrite console itself.

## Have you spent some time to check if this issue has been raised before?

Yes. I talked with two users (including @Meldiron) on discord.

## To Reproduce

Setup a basic realtime example. I used the Web SDK. There shouldn't be any other requirements to reproduce this error.

## Expected behaviour

I expected the realtime api to connect to my server without throwing any errors.

## Actual Behavior

The realtime api throws the above error each second.
![image](https://user-images.githubusercontent.com/66096031/133936907-6876e092-d642-49f4-8f33-9c71ed5de4c9.png)
_Taken from the Appwrite console_

## Your Environment

I used the Web SDK, with Vite. My SDK version is 4.0.1.
Additional I was able to reproduce this bug in both Chrome and Edge.

**Comment by Meldiron** [comment]
I can confirm I have seen this issue with Websockets disconnecting on my Appwrite 0.10 features demo app https://cookie-clicker-appwrite.netlify.app/

![image](https://user-images.githubusercontent.com/19310830/133936969-a0e861f0-5b08-4b54-a0b5-d6d751d75b39.png)

**Comment by TorstenDittmann** [comment]
This should be fixed now with the new Web SDK version `4.0.2` 👍🏻

**Comment by lucasctd** [comment]
@didair mmm what ports? I am having the same issue here. No idea what's wrong :/

![image](https://user-images.githubusercontent.com/5876679/223914467-cde73a97-77b4-4381-97ad-b781a138bf95.png)

**Comment by lucasctd** [comment]
So It seems to be something related to the setting below on docker-compose:

`- traefik.http.routers.appwrite_realtime_wss.tls.certresolver=dns`

Logs from the traefik container

```
time="2023-02-26T19:00:54Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-26T19:01:04Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-26T19:01:33Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-26T19:13:14Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-26T19:13:17Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-26T19:13:38Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-28T18:58:00Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-28T18:58:02Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-02-28T18:58:24Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
time="2023-03-06T14:44:20Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=appwrite_web
time="2023-03-06T14:44:20Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=appwrite_websecure
time="2023-03-06T14:44:20Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=appwrite_web
time="2023-03-06T14:44:20Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=appwrite_websecure
time="2023-03-06T14:45:16Z" level=info msg="Configuration loaded from flags."
time="2023-03-06T14:45:22Z" level=error msg="the router appwrite_realtime_wss@docker uses a non-existent resolver: dns"
```

I just have no idea of what I am supposed to put there instead. I've tried to omit the certresolver setting from docker-compose but I am getting the same error as well.

**Comment by TorstenDittmann** [comment]
@lucasctd pretty sure this line is a leftover and can be removed. That shouldn't be the problem 🤔

**Comment by lucasctd** [comment]
@TorstenDittmann I have removed it again with no success, the error message in the traefik container is gone, but I am still getting the same error in my browser console and in the realtime container I see the following:

```
Worker 1 started successfully
Worker 5 started successfully
Worker 3 started successfully
Worker 4 started successfully
Pub/sub connection established (worker: 1)
Pub/sub connection established (worker: 4)
Pub/sub connection established (worker: 3)
Worker 2 started successfully
Pub/sub connection established (worker: 2)
Worker 6 started successfully
Pub/sub connection established (worker: 5)
Worker 0 started successfully
Worker 7 started successfully
Pub/sub connection established (worker: 0)
Worker 8 started successfully
Pub/sub connection established (worker: 6)
Pub/sub connection established (worker: 7)
Worker 9 started successfully
Worker 11 started successfully
Pub/sub connection established (worker: 9)
Pub/sub connection established (worker: 8)
Worker 10 started successfully
Pub/sub connection established (worker: 11)
Pub/sub connection established (worker: 10)
Server started successfully
Connection close: 1
Connection close: 2
Connection close: 3
Connection close: 4
Connection close: 5
Connection close: 6
Connection close: 7
Connection close: 8
Connection close: 9
Connection close: 10
Connection close: 11
Connection close: 12
Connection close: 13
Connection close: 14
Connection close: 15
Connection close: 16
Connection close: 17
Connection close: 18
Connection close: 19
[2023-03-09 23:22:58 *13.1]	NOTICE	ProcessFactory::end() (ERRNO 1005): session#19 is closed
Connection close: 20
```

Any idea of what I could do about it?

Btw I am doing the following to subscribe to a channel:

```ts
const client = new Client()
client.setEndpoint(config.APPWRITE_URL)
            .setProject(config.APPWRITE_PROJECT_ID)
client.subscribe('files', response => console.log)
```

**Comment by TorstenDittmann** [comment]
@lucasctd can you check in your developer tools under network for the websocket connection and check what messages are being exchanged? 👍🏻

**Comment by lucasctd** [comment]
Hi @TorstenDittmann 
So, I don't get any message there
![image](https://user-images.githubusercontent.com/5876679/224380901-f543788c-80b3-4425-a936-cb47d7da32c3.png)

submitted content
![image](https://user-images.githubusercontent.com/5876679/224381117-4e7fda73-0d07-4d4d-846c-fdc69dd12225.png)

**Comment by lucasctd** [comment]
Just to let you folks know. It wasn't connecting because my appwrite instance is served behind a nginx proxy, so I had to map the /v1/realtime location and set the required settings to make a websocket connection works:


```
  location /v1/realtime {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;

      proxy_pass http://localhost:8095/v1/realtime;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
  }
```

After doing that, I was able to connect and receive the messages XD

Thank you @TorstenDittmann for your support.
