### ISSUE TITLE
🚀 Feature: SSH Key management for OpenRuntime/Functions

### ISSUE THREAD

**Issue by radvansky-tomas** [appwrite/appwrite#3207]
### 🔖 Feature description

I think we should be able to add SSH key to functions...

So functions can get private dependencies

### 🎤 Pitch

I have shared package between flutter & appwrite

And I want to share code between via package, ideally private package.
But since appwrite does not support relative paths in pubspec (which is reasonable) 

Then other option is private github package for example, but I have no clue how we can add
SSH key there. That should be most likely done in function setting (ie appwrite.json)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
I'm guessing what we can do is reserve an environment variable that we can pass in or allow a configurable path (via `appwrite.json`) to fetch a key file during deployment.

**Comment by radvansky-tomas** [comment]
Yeah I mean that one thing...to add env variable there...

But we still have to add way to add id_rsa file in place...

I've check numerous tutorials about adding it via docker compose/ dockerfile...but since every CF is separate container which is not defined inside those file...but rather created via openruntime...we have no access to modify / create that.

I though of using private package repo such ass jfrog artifactory...but even that will not be possible, as you have to for example in case of dart runtime...call dart CLI tool to pass custom token.

**Comment by radvansky-tomas** [comment]
As temporary solution, I am using local git repository using 
[gogs](https://gogs.io/)

Then passing direct link to Flutter application:
`http://localhost:3000/`

And to Dart Functions:
`http://host.docker.internal:3000/` 

Which works for now, once I want to deploy it...I guess I can deploy gogs as well, till this is resolved. But i really hope that there will be proper solution before I am ready to deploy :)

**Comment by r-dev-limited** [comment]
Yeah, I still dont know how to manage SSH keys, specially in digital ocean deployment. 

How to pass ssh key to container -> appwrite -> dart functions
So pub get can obtain private package ?

**Comment by r-dev-limited** [comment]
There is also https://onepub.dev/

Which also require additional steps:
https://docs.onepub.dev/guides/docker

Installing plugin and authentication

**Comment by redarflap** [comment]
I was able to access my private repos by creating an Access token on Github (should also work on Gutlab)
A fine grained type of access token with rea-only permission on content works well. Expires after 1 year max.

Syntax for pubspec.yaml:

`dependencies:
  my_package:
    git:
      url: https://token_name:token@github.com/account/my_package.git
      ref: main
`

**Comment by stnguyen90** [comment]
Btw, Appwrite 1.4's functions now pass env variables during the build. Theoretically, you should be able to set the [NPM_TOKEN](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#set-the-token-as-an-environment-variable-on-the-cicd-server) env var and then the build worker should be able to access the private package
