### ISSUE TITLE
🐛 Bug Report: Missing JWT headers in Functions execution

### ISSUE THREAD

**Issue by va2ron1** [appwrite/appwrite#7247]
### 👟 Reproduction steps

Create an Execution 
```javascript
const client = new Client();
const functions = new Functions(client);
client.setEndpoint(APPWRITE_ENDPOINT)
      .setProject(APPWRITE_PROJECT_ID)
      .setJWT(JWT_TOKEN)
      .setSelfSigned();

const execution = await functions.createExecution(
  FUNCTION_ID,
  undefined,
  false,
  REQUEST_PATH,
  'GET', 
  {
    'example_param': 'value'
  }
);

console.log(execution);
```

### 👍 Expected behavior

Do my request or return my requested values.

### 👎 Actual Behavior

Executing a function using the SDK does not pass through the JWT header from the client or any headers assigned in the createExecution. At a minimum, it should pass 'x-appwrite-jwt', 'x-appwrite-user-jwt', and/or the 'example_param' parameter.

Executing a function using the endpoint without the SDK, for example using fetch, works as expected.

```javascript
const response = await fetch(`https://payment.oorstore.com/paymentMethods`, {
  method: 'GET',
   headers: {
     'x-appwrite-jwt': jwt
   }
});
// At the server function, I received the header as expected.
```

Examining the [source code](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/public/sdk-web/services/functions.ts#L95), it appears that the implementation of the headers option is not fully completed, contrary to what is indicated in the [documentation](https://appwrite.io/docs/references/cloud/client-web/functions#createExecution).

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite Self-Hosted
**Version**: 1.4.13

Running in Docker Desktop

Appwrite Node SDK
**Version**: 11.1.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by va2ron1** [comment]
1. I was looking into the wrong SDK source code, and I found out that everything is implemented.
2. This behavior is [implemented](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/functions.php#L1679) but is fixed to version 2, and right now the version is v3. Before 1.3.8 (which I believe is the version), there was no default value in the [configuration](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/config/collections.php#L2031) file, and the default value was assigned in the [implementation](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/functions.php#L1538). Since there is now a default value in the configuration file, that part of the implementation is ignored, causing it to behave like version 1 (or non-versioned) instead of the current version.

**Comment by stnguyen90** [comment]
@va2ron1, thanks for creating this issue! 🙏🏼 

> 1. I was looking into the wrong SDK source code, and I found out that everything is implemented.
> 2. This behavior is [implemented](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/functions.php#L1679) but is fixed to version 2, and right now the version is v3. Before 1.3.8 (which I believe is the version), there was no default value in the [configuration](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/config/collections.php#L2031) file, and the default value was assigned in the [implementation](https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/functions.php#L1538). Since there is now a default value in the configuration file, that part of the implementation is ignored, causing it to behave like version 1 (or non-versioned) instead of the current version.

Sorry, I don't quite follow...Is there still a problem? If so, what is it exactly?

**Comment by va2ron1** [comment]
@stnguyen90 Yes, I am still experiencing the issue; I simply ignored it for a few days. To put it simply, there is a lack of consistency in the processed request data when creating a function execution via HTTP compared to using the SDK, even though both employ JWT. The HTTP request method works well, and in the request data, you can find (x-appwrite-user-id, x-appwrite-jwt). However, with the SDK, this is not the case. As I previously mentioned, upon examining the source code, I noticed an implementation where these details are exposed as Environment Variables. This, too, isn't working because it is fixed to v2 (there never was a v2; it jumped from nothing to v3).

**Comment by stnguyen90** [comment]
The Appwrite backend will automatically set the JWT and User ID. The code is here: 

https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/functions.php#L1594-L1599

It looks like it's because you're executing with a JWT:

```javascript
const client = new Client();
const functions = new Functions(client);
client.setEndpoint(APPWRITE_ENDPOINT)
      .setProject(APPWRITE_PROJECT_ID)
      .setJWT(JWT_TOKEN)
      .setSelfSigned();

const execution = await functions.createExecution(
  FUNCTION_ID,
  undefined,
  false,
  REQUEST_PATH,
  'GET', 
  {
    'example_param': 'value'
  }
);

console.log(execution);
```

but the session isn't extracted correctly in that case:

https://github.com/appwrite/appwrite/blob/5a715ff68cba4171bf3473eabc83b84a4ae5876c/app/controllers/api/functions.php#L1578-L1583
